spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:internshipdb;DB_CLOSE_DELAY=-1}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true

server:
  port: 8080
  server-header: InternshipTool

logging:
  level:
    org.springframework: INFO
